#!/usr/bin/env bash
# transfers a file from our client to a server

# check if the user provided the correct number of arguments
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3"@"$2":~/
fi
