#!/usr/bin/env bash
# install nginx and listening on port 80 in server
sudo apt-get update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start;
