#!/usr/bin/env bash
# install nginx and listening on port 80 in server
sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
# remove default html example and create new index.html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start;
