#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=10

while [ $counter -gt 0 ]
	do
		
		if [ $counter -eq 1 ]
		then
			echo "Hi"
		fi
		counter=$(( counter - 1 ))
		echo "Best School"
	done
