#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=0

while [ $counter -lt 10 ]
	do
		(( counter++ ))
		if [ $counter -eq 4 ]
		then
			echo "bad luck"
		elif [ $counter -eq 8 ]
		then
			echo "good luck"
		else
			echo "Best School"
		fi
		
		
	done
