#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

h=0

while [ $h -lt 13 ]
	do
		

		echo "Hour: $h"
		(( h++ ))
		m=0
		while [ $m -lt 59 ]
			do
				(( m++ ))
				echo "$m"
			done
	done
