#!/usr/bin/env bash
# File test operators

counter=0

file="school"
if [ ! -e $file ]
then
	echo "$file does not exist"
	exit
else
	if [ -s $file ]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f $file ]
	then
		echo "$file is a regular file"
	fi
	
fi
