#!/usr/bin/env bash
# run nginx as nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf /run/nginx.pid
sudo chmod u+r /etc/nginx/nginx.conf /run/nginx.pid
sudo pkill "apache2"
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
