#!/usr/bin/env bash
# run nginx as nginx
sudo sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
chmod 444 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
