#!/usr/bin/env bash
# run nginx as nginx
chmod a+r /etc/nginx/nginx.conf
sudo sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
