#!/usr/bin/env bash
# run nginx as nginx
sudo sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo pkill "apache2"
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
